# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - dataset: imagenet
  - task: img2img
  - model: vqvae
  - train: default
  - logger: wandb
  - strategy: deepspeed
  - trainer: train
  - paths: default
  - hydra: default

project_name: MinVQVAE
task_name: img2img-vqvae-imagenet
