# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - dataset: mnist
  - task: img2img
  - model: vanilla_vae
  - train: default
  - logger: wandb
  - strategy: deepspeed
  - trainer: train
  - paths: default
  - hydra: default

project_name: VanillaVAE
task_name: img2img-vae-mnist
